version: 2
project_name: rticker
before:
  hooks:
    - go mod tidy
builds:
  -
    skip: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^release:'
source:
  enabled: false
